# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QNIMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'QNRTCKit'
   pod 'Masonry'
   pod 'MJExtension'
   pod 'YYCategories'
   pod 'SDWebImage'
   pod 'AFNetworking'
   pod 'MBProgressHUD'
   pod 'IQKeyboardManager'

  # Pods for QNIMDemo

  target 'QNIMDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QNIMDemoUITests' do
    # Pods for testing
  end

end
